### PR TITLE
Add non-Rails support

### LINKED ISSUE #65: Allow grade_runner to run in non-Rails apps

### PR DESCRIPTION
**Pull request by jelaniwoods**
Resolves #65 

## Problem

In the efforts to come up with one Gemfile for the entire "appdev" course, it would simplify things if `grade_runner` and `ruby_grade_runner` were unified into one gem instead of having to install both and remove one depending on which project is being worked on.

The main reason for the two gems was because `grade_runner` was assumed to be installed in a Rails app and didn't properly load methods from active support that were being used.

## Solution

This PR:
- Adds `activesupport` as a runtime dependency
- Adds `rake` as a runtime dependency
- Only loads Railite when in Rails environment
- Only migrates test database when in Rails environment
- Updates file paths to work in both Rails and non-Rails environments
- Bumps `oj` gem version to deal with Ruby 3 deprecation warning
- Properly loads required gems in non-Rails environment

An unrelated change I added was the ability to record the GitHub username of the person running `rails grade`. Previously, this was just reporting the full name of the user from the local Git config. In this PR I've added an API call to GitHub to retrieve the username and fallback to the full name if one is not found.

I've also bumped the gem version

## Test

Install this version of the gem

```
gem "grade_runner", github: "firstdraft/grade_runner", branch: "65-jw-add-non-rails-support"
```

### Rails

You should be all set! Just run `rails grade` again as usual.

### non-Rails

Update `bin/rails` to find `grade_runner` instead of `ruby_grade_runner`.
```rb
#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'rake'

dir = Gem::Specification.find_by_name('grade_runner').gem_dir

load "#{dir}/lib/tasks/grade.rake"
task_name = ARGV[0]

Rake::Task[task_name].invoke
```
then `bin/rails grade` as usual.

### CODE REVIEW

**Comment by bpurinton** [comment]
@jelaniwoods I'm trying to get a sinatra app grading via either Gitpod or Codespaces (preferably both) with `rails grade`. I made the repo, added specs, and put it on the testing canvas and am trying both Gitpod and Codespaces; but I keep getting a permission denied error that I can't seem to debug. Is my repo setup missing something? I based the file structure (e.g. `bin/` folder) off of the ruby-string chapter (non-rails based).

image

[Here is the repo](https://github.com/appdev-projects/rps-rcav-sinatra)

[And here is the Canvas launcher to test with the rails grade token](https://canvas.instructure.com/courses/5070637/assignments/37092590?module_item_id=84321196)

**Comment by jelaniwoods** [comment]
> I keep getting a permission denied error that I can't seem to debug. 

@bpurinton this sounds like [a file permissions issue](https://linuxhandbook.com/make-file-executable/) that can be resolved by making `bin/rails` executable. You can do this by running `chmod 755 bin/rails`, and then `bin/rails grade` should run.

**Comment by bpurinton** [comment]
D'oh. I was trying `sudo` to get around it; forgot all about `chmod`. Everything runs beautifully with `bin/rails grade`. But, we are likely going to change grading to `rake grade`. Is that something we will change in this repo (maybe on a separate PR) or is that a change that will be made somewhere in the `bin/` files for each project repo?

**Comment by jelaniwoods** [comment]
> we are likely going to change grading to rake grade

@bpurinton Nothing about this gem needs to change for `rake grade` to work.

In Rails apps, the `grade` is already loaded as a Rake task that can be run by either `rails grade` or `rake grade`.

In non-Rails apps, `bin/rails` is just named to be consistent with Rails apps, but you can name the file _anything_ including `bin/rake` if you want.

Does that help clarify?

**Comment by bpurinton** [comment]
Thanks for clarifying things here! I think I've fully gotten my head around `grade_runner` finally. And this change LGTM in case that wasn't clear.

**Pull request merged**
